create web directory ./checkpoints/ellen_scatteing_test/web...
learning rate 0.0002000 -> 0.0002000
/home/guest1/.conda/envs/ellen/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "/home/guest1/ellen_code/pytorch-CycleGAN-and-pix2pix_ellen/data/__init__.py", line 104, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/guest1/.conda/envs/ellen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/guest1/.conda/envs/ellen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/guest1/.conda/envs/ellen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/guest1/.conda/envs/ellen/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/guest1/.conda/envs/ellen/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 235, in _worker_loop
    init_fn(worker_id)
  File "/home/guest1/ellen_code/pytorch-CycleGAN-and-pix2pix_ellen/data/__init__.py", line 65, in seed_worker
    np.random.seed(worker_seed)
  File "mtrand.pyx", line 246, in numpy.random.mtrand.RandomState.seed
  File "_mt19937.pyx", line 166, in numpy.random._mt19937.MT19937._legacy_seeding
  File "_mt19937.pyx", line 180, in numpy.random._mt19937.MT19937._legacy_seeding
ValueError: Seed must be between 0 and 2**32 - 1